# module du helios launcher
name: Launcher Build
on:
  push:
    branches: [ master ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_id: ${{ steps.create_release.outputs.release_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # ✅ Version mise à jour

      - name: Get version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_ENV
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: release ${{ env.version }}
          draft: false
          prerelease: ${{ contains(env.version, 'beta') || contains(env.version, 'alpha') }}

  build-launcher:
    needs: create-release
    strategy:
      matrix:
        os: [macos-14, ubuntu-latest, windows-2022]  # ✅ windows-latest → windows-2022

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4  # ✅ Version mise à jour

      - name: Set up Node
        uses: actions/setup-node@v4  # ✅ Version mise à jour
        with:
          node-version: 20.x

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm ci

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ✅ Correction du nom du secret
        run: npm run build
